### ISSUE TITLE
Error on CiviCRM 5.0.0

### ISSUE THREAD

**Issue by homotechsual** [woolman/genderselfidentify#4]
The extension produces the following error on Civicrm 5.0.0

```
[11-Apr-2018 22:12:18 Europe/London] PHP Fatal error:  Uncaught Error: Class 'CRM_Genderselfidentify_ContactAPIWrapper' not found in /sites/default/files/civicrm/ext/org.woolman.genderselfidentify/genderselfidentify.php:111
Stack trace:
#0 /sites/all/modules/civicrm/CRM/Utils/Hook.php(274): genderselfidentify_civicrm_apiWrappers(Array, Array)
#1 /sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(84): CRM_Utils_Hook->runHooks(Array, 'civicrm_apiWrap...', 2, Array, Array, NULL, NULL, NULL, NULL)
#2 /sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, Array, Array, NULL, NULL, NULL, NULL, 'civicrm_apiWrap...')
#3 [internal function]: Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), 'hook_civicrm_ap...', Object(Civi\Core\CiviEventDispatcher))
#4 /sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventD in /sites/default/files/civicrm/ext/org.woolman.genderselfidentify/genderselfidentify.php on line 111
```

**Comment by colemanw** [comment]
Hey @MikeyMJCO is this still a problem? Looks like it could be a post-upgrade cache issue.

**Comment by homotechsual** [comment]
Yeah, sorry @colemanw I forgot to come back an close this - my bad. Post-upgrade cache issue indeed.
